steps:
  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "pip"]

  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", "-r", "requirements.txt"]

  - name: 'gcr.io/cloud-builders/pip'
    args: ['wheel', '.', '--wheel-dir=build']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'build/*.whl', 'gs://python-packages-89q34hae/test']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['artifacts', 'python', 'upload', '--location', 'us-central1', 'gs://python-packages-89q34hae/test/*.whl']